# Generated by Django 3.2 on 2022-12-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221206_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental_id',
            new_name='rental',
        ),
    ]
