# Generated by Django 3.2 on 2022-12-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_rental_id_reservation_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='base.rental'),
        ),
    ]
