# Generated by Django 3.2 on 2022-12-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_reservation_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rental'),
        ),
    ]
