# Generated by Django 3.2 on 2022-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_reservation_rental'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['checkin'], name='base_reserv_checkin_35aa57_idx'),
        ),
    ]
