# Generated by Django 3.2 on 2022-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reservation_base_reserv_checkin_35aa57_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='base_reserv_checkin_35aa57_idx',
        ),
    ]
